Use the X-Simperium-API-Key header and json data to fix authenticating to the simperium API
swalladge/simperium-python3 pull request #1
Opened 2021-07-05 18:03 UTC by giuli007

Originally noticed when using sncli that stopped being able to login this weekend.
I opened https://github.com/insanum/sncli/issues/109

After a bit of digging I found a similar project using the `X-Simperium-API-Key` header instead of a `client_id` in the data body https://github.com/simplenote-vim/simplenote.py/blob/master/simplenote/simplenote.py#L78 

This PR uses a similar approach and I managed to make sncli work with this.

2021-07-05 18:08 UTC, giuli007 commented
@swalladge let me know if this looks ok to merge in and release a new version or if you need anything else
Something must have changed on the simperium API and deprecated the old authentication method.

2021-07-05 18:33 UTC, noooxxi commented
So do we just wait? Or, what can an sncli user do to be able to log back in again?

2021-07-05 20:41 UTC, giuli007 commented
> So do we just wait? Or, what can an sncli user do to be able to log back in again?

@noooxxi I've put a suggestion on how you could try to run sncli with the fix directly from source on https://github.com/insanum/sncli/issues/109#issuecomment-874319604 if you feel like doing that.

2021-07-05 22:47 UTC, swalladge commented
@roundhill could you confirm if there have been breaking changes with the simperium api recently?  Should the API key be passed in the `X-Simperium-API-Key` header (the method proposed here) or the `client_id` field in the request body (the current method)?

@giuli007 reports that the `client_id` method no longer works, but it works for me testing right now.

2021-07-06 17:31 UTC, roundhill commented
Hi, I pinged the Simperium devs to take a look I'm working on other things these days.

2021-07-06 17:47 UTC, eshurakov commented
Hi there, please take a look at the following API Reference: https://simperium.com/docs/reference/http/#auth
For auth requests API Key should be passed in `X-Simperium-API-Key` and request body should be JSON encoded.
For API requests auth token should be passed in `X-Simperium-Token`.

2021-07-06 22:56 UTC, swalladge commented
@roundhill @eshurakov awesome, thank you! For some reason I didn't think of looking around for official docs.

@eshurakov by the way, is https://github.com/Simperium/simperium-python no longer maintained?  I checked there first but it hasn't changed since 2018 and doesn't use these auth headers.  Would there be any interest in upstreaming this fork?

2021-07-06 22:59 UTC, swalladge requested changes

2021-07-06 22:59 UTC, swalladge commented on simperium/core.py
> +        headers = {'X-Simperium-API-Key': self.api_key}
@giuli007 could you also implement this change for the `Auth.create` method?

2021-07-07 13:57 UTC, giuli007 commented on simperium/core.py
> +        headers = {'X-Simperium-API-Key': self.api_key}
Updated PR and done that.

However it is worth noting that I was not able to confirm this will work as I was not able to successfully use the `create` endpoint. 

I also tried by simply curling it like explained in the docs but I keep getting `401` with `invalid app credentials`
```
curl -H 'X-Simperium-API-Key: 26864ab5d6fd4a37b80343439f107350' -d '{"username":"test12345@mt2015.com","password":"test"}' https://auth.simperium.com/1/chalk-bump-f49/create/
invalid app credentials
```
nb I also tried with a more proper personal email just in case the issue was with the email used as username.

2021-07-07 18:31 UTC, eshurakov commented on simperium/core.py
> +        headers = {'X-Simperium-API-Key': self.api_key}
@giuli007 this API Key is an "auth only" key and can't create user accounts. Simplenote now requires email to be verified before account is created. The only option to create an account is to do it on the web https://app.simplenote.com/signup/.  
After that email/password can be used to log-in and get an auth token.

2021-07-07 19:43 UTC, eshurakov commented
@swalladge It doesn't look like https://github.com/Simperium/simperium-python is maintained. I actually wasn't aware about this library, we're mostly using those for iOS and Android.
PRs are always welcome! We're a bit short handed at the moment and focused on the server maintenance, so it may take some time :-)
Thank you!

2021-07-07 23:17 UTC, swalladge commented on simperium/core.py
> +        headers = {'X-Simperium-API-Key': self.api_key}
Thanks!

> The only option to create an account is to do it on the web 

Ah that's good to know, thanks.

2021-07-07 23:20 UTC, swalladge approved these changes

2021-07-07 23:21 UTC, merged

2021-07-08 00:09 UTC, swalladge commented
@eshurakov I'm happy to open a PR, but the diff will be huge.  The major changes in this fork are: migrate from python2 to python3 in a non backwards compatible manner, and using the requests library for api requests (improves code readability and error handling).  Please let me know how/if you'd like me to work to contribute this upstream.

2021-07-11 17:48 UTC, eshurakov commented
@swalladge sorry for the delay. I will need to check a few things and then get back to you!

2021-07-13 07:23 UTC, eshurakov commented
@swalladge We use python simperium library in some internal projects that are hard to update to python3 at the moment. To avoid accidental breakage I think it's better to keep python3 implementation as a separate project / library. At least for now :-)

If you have any Simperium related questions, feel free to tag me.
Thank you!

2021-07-13 07:32 UTC, swalladge commented
@eshurakov sure no worries. :+1: